spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
app.upload.dir=${APP_UPLOAD_DIR}
app.frontend.url=${FRONTEND_URL}





jwt.expiration=3600000



spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=mvbx430@gmail.com
spring.mail.password=grwvziasnhnzavme

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true