spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
app.upload.dir=${APP_UPLOAD_DIR}
app.frontend.url=${FRONTEND_URL}





jwt.expiration=3600000


# ==========================================
# SPRING AI 2.0 GOOGLE GENAI (PRODUCTION)
# ==========================================
spring.ai.model.chat=google-genai
spring.ai.model.embedding=google-genai
spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.chat.model=gemini-2.5-flash

spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=mvbx430@gmail.com
spring.mail.password=grwvziasnhnzavme

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.vectorstore.path=${VECTORSTORE_PATH}

spring.ai.google.genai.project-id=802194466507
spring.ai.google.genai.location=us-central1